apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret
  namespace: panigrahan

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: avvak
  MYSQL_USER: panigrahan
  MYSQL_PASSWORD: panigrahan123